"""empty message

Revision ID: dcbee03e3639
Revises: 
Create Date: 2018-07-10 04:25:35.968792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcbee03e3639'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('token_hash', sa.Text(), nullable=True),
    sa.Column('salt', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploader', sa.Integer(), nullable=True),
    sa.Column('ipfs_hash', sa.Text(), nullable=True),
    sa.Column('original_name', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uploader'], ['credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint("uploader_ipfs_constraint", "uploads", ["uploader", "ipfs_hash"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploads')
    op.drop_table('credentials')
    op.drop_constraint("uploader_ipfs_constraint", "uploads")
    # ### end Alembic commands ###
