version: "2.4" # Using 2.4 since 3+ mem_limit is no longer viable.
services:
  ipfs:
    hostname: ipfs
    container_name: ipfs
    image: ipfs/go-ipfs:v0.4.15
    mem_limit: 512m # more stuff goes through the node
    volumes:
      - /var/dbdata/ipfs_staging:/data/ipfs
      - /var/dbdata/ipfs_export:/export
    environment:
      - API_ORIGIN=upload-point
      - API_ORIGIN=localhost
       # Find a way to do this in the non-deprivated way in the future
    ports: 
      - "4001:4001"
      - "127.0.0.1:5001:5001" # ONLY local
      - "8080:8080" 
      - "4002:4002/udp"
  db:
    hostname: db
    container_name: psql
    restart: on-failure:5
    image: postgres:10
    mem_limit: 256m #bump up if necessary
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - DEBUG=false
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hifi
    volumes: 
      - /var/dbdata/postgres:/var/lib/postgresql

  upload-point:
    hostname: upload-point
    container_name: file_uploader
    build: ./
    mem_limit: 512m # Processes zip files
    depends_on:
      - ipfs
      - db
    ports: 
      - "80:80"
    environment:
      - FLASK_APP=/app/main.py
      - SECRET_KEY=${SECRET_KEY}
      - UPLOAD_FOLDER=/tmp/uploads/ #Folder where files are temporary uploaded to be unpacked.
      - DATABASE_URI=postgresql://postgres:postgres@db:5432/hifi

      