
# This compose file is used mostly for developing as it uses volumes instead of strict paths. 

version: "2.4" # Using 2.4 since 3+ mem_limit is no longer viable.
services:
  ipfs:
    hostname: ipfs
    container_name: ipfs
    image: ipfs/go-ipfs:v0.4.15
    mem_limit: 512m # more stuff goes through the node
    volumes:
      - "ipfs_data:/data/ipfs"
      - "ipfs_staging:/export"
    environment:
      - API_ORIGIN=gatekeeper
      - API_ORIGIN=localhost
       # Find a way to do this in the non-deprivated way in the future
    ports: 
      - "4001:4001"
      - "127.0.0.1:5001:5001" # ONLY local
      - "127.0.0.1:8080:8080" 
      - "4002:4002/udp"

  db:
    hostname: db
    container_name: psql
    restart: on-failure:5
    image: postgres:10
    mem_limit: 250m #bump up if necessary

    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - DEBUG=false
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hifi
    volumes: 
      - dbdata:/var/lib/postgresql

  gatekeeper:
    hostname: gatekeeper
    container_name: gatekeeper
    build: ./
    mem_limit: 512m # Processes zip files
    depends_on:
      - ipfs
      - db
    ports: 
      - "80:80"
    #  - "443:443" # Remove the Comments if you want to use HTTPS connections
    #volumes:  
    #  - /etc/letsencrypt/:/etc/letsencrypt/:ro 
    environment:
      - FLASK_APP=/app/main.py
      - SECRET_KEY=${SECRET_KEY}
      - UPLOAD_FOLDER=/tmp/uploads/ #Folder where files are temporary uploaded to be unpacked.
      - DATABASE_URI=postgresql://postgres:postgres@db:5432/hifi
 
volumes:
  ipfs_staging:
  ipfs_data:
  dbdata:
